# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qbconf < Formula
  desc ""
  homepage "https://github.com/RaftechNL/qbconf"
  version "0.0.16"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/RaftechNL/qbconf/releases/download/0.0.16/qbconf_darwin_arm64.tar.gz"
      sha256 "5e778677e8c25a58f556410072401a3a86d3c7093005cff1a578b689293526d4"

      def install
        mv 'qbconf_darwin_arm64', 'qbconf'
        bin.install "qbconf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/RaftechNL/qbconf/releases/download/0.0.16/qbconf_darwin_amd64.tar.gz"
      sha256 "2286fb2bc134dc760946b89a7e224c81dfc04c3f550582f6ce2dbff019530fc3"

      def install
        mv 'qbconf_darwin_amd64', 'qbconf'
        bin.install "qbconf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RaftechNL/qbconf/releases/download/0.0.16/qbconf_linux_arm64.tar.gz"
      sha256 "93f88108d11f8edbc44da1d50765adfe7bba7c6f834d2ceaaabfd352866d3b02"

      def install
        mv 'qbconf_linux_arm64', 'qbconf'
        bin.install "qbconf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/RaftechNL/qbconf/releases/download/0.0.16/qbconf_linux_amd64.tar.gz"
      sha256 "a9c17ae6bd53a96d1148c3d424d3b2bfaefd82d3d4c040ac492e1301cb16b38a"

      def install
        mv 'qbconf_linux_amd64', 'qbconf'
        bin.install "qbconf"
      end
    end
  end
end
