# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qbconf < Formula
  desc ""
  homepage "https://github.com/RaftechNL/qbconf"
  version "0.0.11"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/RaftechNL/qbconf/releases/download/0.0.11/qbconf_darwin_arm64.tar.gz"
      sha256 "bf7a65a5d8d775cd9c136ee255b0ab60a954ae8b93dfb7300f437a1a338dfabb"

      def install
        bin.install "darwin_arm64_qbconf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/RaftechNL/qbconf/releases/download/0.0.11/qbconf_darwin_amd64.tar.gz"
      sha256 "8d973bed970138331603a85f40de298040874d4fe89095dc51c6012209a0f02c"

      def install
        bin.install "darwin_amd64_qbconf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RaftechNL/qbconf/releases/download/0.0.11/qbconf_linux_arm64.tar.gz"
      sha256 "b55544cc717f4f1d37eff49bef0c996a62f0ff247697409d44903d9d15e2094b"

      def install
        bin.install "linux_arm64_qbconf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/RaftechNL/qbconf/releases/download/0.0.11/qbconf_linux_amd64.tar.gz"
      sha256 "b163e88a54b03e6ed850177c3b39843c86cb3c8ff0d5a39860ffe1a919782a0c"

      def install
        bin.install "linux_amd64_qbconf"
      end
    end
  end
end
