# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ym < Formula
  desc ""
  homepage "https://github.com/RaftechNL/ym"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/RaftechNL/ym/releases/download/v0.1.1/ym_0.1.1_Darwin_arm64.tar.gz"
      sha256 "624bef2fe75d3feec174935090652272d3e045dd81bcfe1ded07e1613676fc02"

      def install
        bin.install "ym"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/RaftechNL/ym/releases/download/v0.1.1/ym_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "21890cd3764522719553b65f75f48e086a27e00cd9a4ff040d753441ae63164a"

      def install
        bin.install "ym"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/RaftechNL/ym/releases/download/v0.1.1/ym_0.1.1_Linux_armv6.tar.gz"
      sha256 "b633419fea824f0fbe3fd8fc6daeb3fb79a0775026a9ef1d210476e018df70d7"

      def install
        bin.install "ym"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RaftechNL/ym/releases/download/v0.1.1/ym_0.1.1_Linux_arm64.tar.gz"
      sha256 "2d33dbed16f30de5c7b6ed443b472d83b7520e53cf5bb0d20c1f45033ddcd2a1"

      def install
        bin.install "ym"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/RaftechNL/ym/releases/download/v0.1.1/ym_0.1.1_Linux_x86_64.tar.gz"
      sha256 "70dd0c1b9cddf0bac77085dffa852632f525e8ddcceaba54fd3efc088a18434f"

      def install
        bin.install "ym"
      end
    end
  end
end
